# Form implementation generated from reading ui file 'ui/slave_configuration_dialog/slave_configuration_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SlaveConfigDialog(object):
    def setupUi(self, SlaveConfigDialog):
        SlaveConfigDialog.setObjectName("SlaveConfigDialog")
        SlaveConfigDialog.resize(537, 458)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SlaveConfigDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=SlaveConfigDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(parent=SlaveConfigDialog)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=SlaveConfigDialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(parent=SlaveConfigDialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(parent=SlaveConfigDialog)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_3.addWidget(self.radioButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=SlaveConfigDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.spinBox_2 = QtWidgets.QSpinBox(parent=SlaveConfigDialog)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_4.addWidget(self.spinBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=SlaveConfigDialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.spinBox_3 = QtWidgets.QSpinBox(parent=SlaveConfigDialog)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_5.addWidget(self.spinBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SlaveConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_6.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(SlaveConfigDialog)
        self.buttonBox.accepted.connect(SlaveConfigDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(SlaveConfigDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SlaveConfigDialog)

    def retranslateUi(self, SlaveConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        SlaveConfigDialog.setWindowTitle(_translate("SlaveConfigDialog", "Dialog"))
        self.label.setText(_translate("SlaveConfigDialog", "Slave ID:"))
        self.label_2.setText(_translate("SlaveConfigDialog", "Function:"))
        self.comboBox.setItemText(0, _translate("SlaveConfigDialog", "03 Read Holding Registers (4x)"))
        self.groupBox.setTitle(_translate("SlaveConfigDialog", "Address mode"))
        self.radioButton.setText(_translate("SlaveConfigDialog", "Dec"))
        self.radioButton_2.setText(_translate("SlaveConfigDialog", "Hex"))
        self.label_3.setText(_translate("SlaveConfigDialog", "Slave address:"))
        self.label_4.setText(_translate("SlaveConfigDialog", "Quantity:"))
