# Form implementation generated from reading ui file '.\ui\home\home.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(800, 600)
        icon = QtGui.QIcon.fromTheme("network-wired")
        Home.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Home)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.exitBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.gridLayout.addWidget(self.exitBtn, 4, 0, 1, 2)
        self.docBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.docBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.docBtn.setFont(font)
        self.docBtn.setObjectName("docBtn")
        self.gridLayout.addWidget(self.docBtn, 3, 0, 1, 2)
        self.modbusMasterBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.modbusMasterBtn.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Sans")
        font.setPointSize(24)
        self.modbusMasterBtn.setFont(font)
        self.modbusMasterBtn.setObjectName("modbusMasterBtn")
        self.gridLayout.addWidget(self.modbusMasterBtn, 2, 1, 1, 1)
        self.titleLbl = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(52)
        font.setBold(True)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.gridLayout.addWidget(self.titleLbl, 1, 0, 1, 2)
        self.modbusSlaveBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.modbusSlaveBtn.setEnabled(True)
        self.modbusSlaveBtn.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Sans")
        font.setPointSize(24)
        self.modbusSlaveBtn.setFont(font)
        self.modbusSlaveBtn.setObjectName("modbusSlaveBtn")
        self.gridLayout.addWidget(self.modbusSlaveBtn, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\ui\\home\\../../resources/icons/modbus.png"))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Modbus JC"))
        self.exitBtn.setText(_translate("Home", "Exit"))
        self.docBtn.setText(_translate("Home", "Documentation"))
        self.modbusMasterBtn.setText(_translate("Home", "Modbus Master"))
        self.titleLbl.setText(_translate("Home", "MODBUS JC"))
        self.modbusSlaveBtn.setText(_translate("Home", "Modbus Slave"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec())
