# Form implementation generated from reading ui file '.\ui\registers_widget\registers_widget.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegistersWidget(object):
    def setupUi(self, RegistersWidget):
        RegistersWidget.setObjectName("RegistersWidget")
        RegistersWidget.resize(303, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(RegistersWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=RegistersWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(RegistersWidget)
        QtCore.QMetaObject.connectSlotsByName(RegistersWidget)

    def retranslateUi(self, RegistersWidget):
        _translate = QtCore.QCoreApplication.translate
        RegistersWidget.setWindowTitle(_translate("RegistersWidget", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("RegistersWidget", "0"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("RegistersWidget", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("RegistersWidget", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("RegistersWidget", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("RegistersWidget", "4"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("RegistersWidget", "5"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("RegistersWidget", "6"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("RegistersWidget", "7"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("RegistersWidget", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("RegistersWidget", "Value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistersWidget = QtWidgets.QWidget()
    ui = Ui_RegistersWidget()
    ui.setupUi(RegistersWidget)
    RegistersWidget.show()
    sys.exit(app.exec())
